=== ArturPrzybysz/pkck/src/main/java/pkck/Model/main.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:main="http://www.przyklad.pl/main" targetNamespace="http://www.przyklad.pl/main">
    <element name="document">
        <complexType>
            <sequence>
                <element name="authors" type="main:authors" minOccurs="1" maxOccurs="1" />
                <element name="racePrefs" type="main:racePrefs" minOccurs="1" maxOccurs="1" />
                <element name="typePrefs" type="main:typePrefs" minOccurs="1" maxOccurs="1" />
                <element name="itemPrefs" type="main:itemPrefs" minOccurs="1" maxOccurs="1" />
                <element name="creatures" type="main:creatures" minOccurs="1" maxOccurs="1" />
            </sequence>
        </complexType>
        <key name="raceId">
            <selector xpath="./racePrefs/racePref" />
            <field xpath="@raceId" />
        </key>
        <keyref name="raceIdRef" refer="main:raceId">
            <selector xpath="./creatores/creature" />
            <field xpath="@raceId" />
        </keyref>
    </element>
    
    <complexType name="authors">
        <sequence>
            <element name="author" maxOccurs="2" type="main:authorFinal" />
        </sequence>
    </complexType>
    
    <complexType name="racePrefs">
        <sequence>
            <element name="racePref" minOccurs="1" maxOccurs="unbounded" type="main:racePrefType" />
        </sequence>
    </complexType>
    
    <complexType name="typePrefs">
        <sequence>
            <element name="typePref" minOccurs="1" maxOccurs="unbounded" type="main:typePrefType" />
        </sequence>
    </complexType>
    
    <complexType name="itemPrefs">
        <sequence>
            <element name="itemPref" minOccurs="1" maxOccurs="unbounded" type="main:itemPrefType" />
        </sequence>
    </complexType>
    
    <complexType name="creatures">
        <sequence>
            <element name="creature" type="main:creature" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    
    <complexType name="creature">
        <sequence>
            <element name="nick" type="string" minOccurs="1" maxOccurs="1" />
            <element name="race" type="string" minOccurs="1" maxOccurs="1" />
            <element name="type" type="string" minOccurs="1" maxOccurs="1" />
            <element name="level" type="integer" minOccurs="1" maxOccurs="1" />
            <element name="money" type="main:money" minOccurs="1" maxOccurs="1" />
            <element name="creationDate" type="date" minOccurs="1" maxOccurs="1" />
            <element name="equipment" type="main:equipment" minOccurs="1" maxOccurs="1" />
        </sequence>
        <attribute name="raceId" type="string" use="required" />
        <attribute name="typeId" type="string" use="required" />
        <attributeGroup ref="main:teamAttributes" />
    </complexType>
    
    <complexType name="equipment">
        <sequence minOccurs="0">
            <element name="item" maxOccurs="unbounded" minOccurs="0" type="main:equipmentType" />
        </sequence>
    </complexType>
    
    <complexType name="racePrefType">
        <attribute name="raceId" type="string" />
        <attribute name="name" type="string" />
    </complexType>
    
    <simpleType name="authorNameType">
        <restriction base="string">
            <pattern value="[A-Z]([a-z])+" />
        </restriction>
    </simpleType>
    
    <simpleType name="indexNumberType">
        <restriction base="integer">
            <pattern value="[0-9]{6}" />
        </restriction>
    </simpleType>
    
    <complexType name="author">
        <sequence>
            <element name="first_name" type="main:authorNameType" />
            <element name="last_name" type="main:authorNameType" />
            <element name="index_number" type="main:indexNumberType" />
            <element name="birthday" type="date" minOccurs="0" maxOccurs="1" />
        </sequence>
    </complexType>
    
    <group name="nameGroup">
        <sequence>
            <element name="first_name" type="main:authorNameType" />
            <element name="last_name" type="main:authorNameType" />
        </sequence>
    </group>
    
    <complexType name="authorFinal">
        <sequence>
            <group ref="main:nameGroup" />
            <element name="index_number" type="main:indexNumberType" />
            <element name="birthday" type="date" minOccurs="0" maxOccurs="1" />
        </sequence>
    </complexType>
    
    <complexType name="typePrefType">
        <attribute name="typeId" type="string" />
        <attribute name="name" type="string" />
    </complexType>
    
    <complexType name="itemPrefType">
        <attribute name="itemId" type="string" />
        <attribute name="itemType" type="string" use="required" />
        <attribute name="name" type="string" />
    </complexType>
    
    <complexType name="equipmentType">
        <sequence>
            <element type="byte" name="amount" />
            <element type="string" name="name" />
        </sequence>
        <attribute type="string" name="itemId" />
    </complexType>
    
    <simpleType name="team">
        <restriction base="string">
            <enumeration value="czerwony" />
            <enumeration value="niebieski" />
            <enumeration value="zielony" />
        </restriction>
    </simpleType>
    
    <simpleType name="money">
        <restriction base="decimal">
            <fractionDigits value="2" />
        </restriction>
    </simpleType>
    
    <simpleType name="teamRole">
        <restriction base="string">
            <enumeration value="boss" />
            <enumeration value="noob" />
        </restriction>
    </simpleType>
    
    <attributeGroup name="teamAttributes">
        <attribute name="team" type="main:team" />
        <attribute name="role" type="main:teamRole" />
    </attributeGroup>
</schema>

=== ArturPrzybysz/pkck/file.xml
<?xml version="1.0" encoding="UTF-8" ?>
<main:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.przyklad.pl/main main.xsd" xmlns:main="http://www.przyklad.pl/main">
    <authors>
        <author>
            <first_name>Antoni</first_name>
            <last_name>Messyasz</last_name>
            <index_number>210273</index_number>
            <birthday>2002-04-08</birthday>
        </author>
        <author>
            <first_name>Artur</first_name>
            <last_name>Przybysz</last_name>
            <index_number>210301</index_number>
            <birthday>1995-04-29</birthday>
        </author>
    </authors>
    <racePrefs>
        <racePref raceId="_r1" name="human" />
        <racePref raceId="_r2" name="orc" />
        <racePref raceId="_r3" name="elf" />
        <racePref raceId="_r4" name="goblin" />
        <racePref raceId="_r5" name="dwarf" />
        <racePref raceId="_r6" name="creature" />
    </racePrefs>
    <typePrefs>
        <typePref typeId="_c0" name="monster" />
        <typePref typeId="_c1" name="paladin" />
        <typePref typeId="_c2" name="warrior" />
        <typePref typeId="_c3" name="mage" />
        <typePref typeId="_c4" name="archer" />
        <typePref typeId="_c5" name="scout" />
        <typePref typeId="_c6" name="war-mage" />
        <typePref typeId="_c7" name="berserker" />
    </typePrefs>
    <itemPrefs>
        <itemPref itemId="_i0" itemType="weapon" name="hand" />
        <itemPref itemId="_i1" itemType="weapon" name="sword" />
        <itemPref itemId="_i2" itemType="weapon" name="bow" />
        <itemPref itemId="_i3" itemType="weapon" name="rod" />
        <itemPref itemId="_i4" itemType="weapon" name="crossbow" />
        <itemPref itemId="_i5" itemType="weapon" name="zweihander" />
        <itemPref itemId="_i6" itemType="weapon" name="rock" />
        <itemPref itemId="_i7" itemType="food" name="apple" />
        <itemPref itemId="_i8" itemType="food" name="bread" />
        <itemPref itemId="_i9" itemType="food" name="water" />
        <itemPref itemId="_i10" itemType="food" name="cake" />
        <itemPref itemId="_i11" itemType="food" name="peach" />
        <itemPref itemId="_i12" itemType="food" name="beer" />
        <itemPref itemId="_i13" itemType="armor" name="legs" />
        <itemPref itemId="_i14" itemType="armor" name="legs" />
        <itemPref itemId="_i15" itemType="armor" name="head" />
        <itemPref itemId="_i16" itemType="armor" name="body" />
        <itemPref itemId="_i17" itemType="armor" name="boots" />
        <itemPref itemId="_i18" itemType="weapon" name="knife" />
    </itemPrefs>
    <creatures>
        <creature raceId="_r1" typeId="_c2" team="czerwony" role="boss">
            <nick>Johny</nick>
            <race>human</race>
            <type>warrior</type>
            <level>15</level>
            <money>650.00</money>
            <creationDate>2019-03-19</creationDate>
            <equipment>
                <item itemId="_i1">
                    <amount>1</amount>
                    <name>sword</name>
                </item>
                <item itemId="_i14">
                    <amount>1</amount>
                    <name>legs</name>
                </item>
                <item itemId="_i15">
                    <amount>1</amount>
                    <name>head</name>
                </item>
                <item itemId="_i16">
                    <amount>1</amount>
                    <name>body</name>
                </item>
                <item itemId="_i17">
                    <amount>1</amount>
                    <name>boots</name>
                </item>
                <item itemId="_i7">
                    <amount>5</amount>
                    <name>apple</name>
                </item>
            </equipment>
        </creature>
        <creature raceId="_r6" typeId="_c0" team="czerwony" role="noob">
            <nick>Wolf</nick>
            <race>creature</race>
            <type>monster</type>
            <level>10</level>
            <money>100.12</money>
            <creationDate>2019-03-19</creationDate>
            <equipment />
        </creature>
        <creature raceId="_r2" typeId="_c2" team="niebieski" role="boss">
            <nick>Legolas</nick>
            <race>elf</race>
            <type>archer</type>
            <level>30</level>
            <money>12002341.11</money>
            <creationDate>2019-03-19</creationDate>
            <equipment>
                <item itemId="_i2">
                    <amount>1</amount>
                    <name>bow</name>
                </item>
                <item itemId="_i18">
                    <amount>1</amount>
                    <name>knife</name>
                </item>
                <item itemId="_i14">
                    <amount>1</amount>
                    <name>legs</name>
                </item>
                <item itemId="_i15">
                    <amount>1</amount>
                    <name>head</name>
                </item>
                <item itemId="_i16">
                    <amount>1</amount>
                    <name>body</name>
                </item>
                <item itemId="_i17">
                    <amount>1</amount>
                    <name>boots</name>
                </item>
            </equipment>
        </creature>
    </creatures>
    </main:document>
